meta:
    site_title: "ODM's Blog"
    site_subtitle: "Study"
    site_language: "en"
    absolute_baseurl: http://www.suruby.com
    domain: www.suruby.com
    author:
        full_name:Liuxiaobo
        short_name: ODM
        name: ODM
        email: odm@sketchupbar.com

url: http://www.suruby.com

#baseurl: /base

markdown: kramdown

# markdown: maruku
# maruku:
#   use_divs: true
#    use_tex: true
#    png_engine : blahtex
#    png_dir    : images/latex/
#    png_url    : /images/latex/

pygments: false
permalink: /blog/:year/:month/:day/:title

disqus_short_name: ypchenstory

lsi: false



